# Generated by Django 5.2.5 on 2025-08-22 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=192)),
                ('file', models.FileField(upload_to='media/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('media_type', models.CharField(choices=[('movie', 'Movie'), ('music', 'Music'), ('photos', 'Photos')], max_length=10)),
                ('duration', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.folder')),
            ],
        ),
    ]
